# It only creates the ec2-instance but not connect to it because the vpc and security group is not specified, i.e in the inbound rules ssh and http port is not enabled
AWSTemplateFormatVersion: "2010-09-09"
Description: Provisioning an ec2-instance via cloudFormation Template

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-04708942c263d8190
      InstanceType: t2.micro


# Also using AWS CLI to create a stack we use this following command
# aws cloudformation create-stack --stack-name ec2-stack --template-body file://C:\Users\sohai\OneDrive\Desktop\Templates\template.yaml 

# And to update the existing stack we use this following command
# aws cloudformation update-stack --stack-name ec2-stack --template-body file://C:\Users\sohai\OneDrive\Desktop\Templates\template.yaml 


      
